name: prewave-challenge
services:
    database:
        image: postgres:17.2
        environment:
            POSTGRES_USER: "${DATABASE_USER:-test}"
            POSTGRES_PASSWORD: "${DATABASE_PASSWORD:-test}"
            POSTGRES_DB: "${DATABASE_NAME:-test}"
        volumes:
            -   './init.sql:/docker-entrypoint-initdb.d/init.sql'
        ports:
            -   "${DATABASE_PORT:-5432}:5432"